# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_drop.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(551, 360)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.hl_path = QtWidgets.QHBoxLayout()
        self.hl_path.setObjectName("hl_path")
        self.le_save_path = QtWidgets.QLineEdit(Dialog)
        self.le_save_path.setObjectName("le_save_path")
        self.hl_path.addWidget(self.le_save_path)
        self.pb_path_browser = QtWidgets.QPushButton(Dialog)
        self.pb_path_browser.setObjectName("pb_path_browser")
        self.hl_path.addWidget(self.pb_path_browser)
        self.verticalLayout.addLayout(self.hl_path)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.le_filename = QtWidgets.QLineEdit(Dialog)
        self.le_filename.setObjectName("le_filename")
        self.horizontalLayout_3.addWidget(self.le_filename)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.le_crc = QtWidgets.QLineEdit(Dialog)
        self.le_crc.setReadOnly(True)
        self.le_crc.setObjectName("le_crc")
        self.gridLayout.addWidget(self.le_crc, 1, 0, 1, 1)
        self.le_file_len = QtWidgets.QLineEdit(Dialog)
        self.le_file_len.setReadOnly(True)
        self.le_file_len.setObjectName("le_file_len")
        self.gridLayout.addWidget(self.le_file_len, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.le_info = QtWidgets.QLineEdit(Dialog)
        self.le_info.setObjectName("le_info")
        self.verticalLayout.addWidget(self.le_info)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.hl_pb_exec = QtWidgets.QHBoxLayout()
        self.hl_pb_exec.setObjectName("hl_pb_exec")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_pb_exec.addItem(spacerItem4)
        self.pb_exec = QtWidgets.QPushButton(Dialog)
        self.pb_exec.setObjectName("pb_exec")
        self.hl_pb_exec.addWidget(self.pb_exec)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hl_pb_exec.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.hl_pb_exec)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_drop = QtWidgets.QVBoxLayout()
        self.verticalLayout_drop.setObjectName("verticalLayout_drop")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_drop.addWidget(self.label)
        self.le_filepath = QtWidgets.QLineEdit(Dialog)
        self.le_filepath.setObjectName("le_filepath")
        self.verticalLayout_drop.addWidget(self.le_filepath)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_drop.addItem(spacerItem6)
        self.horizontalLayout.addLayout(self.verticalLayout_drop)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "文件助手"))
        self.label_2.setText(_translate("Dialog", "保存路径"))
        self.pb_path_browser.setText(_translate("Dialog", "浏览"))
        self.label_3.setText(_translate("Dialog", "文件名"))
        self.label_4.setText(_translate("Dialog", "文件校验"))
        self.label_5.setText(_translate("Dialog", "文件长度"))
        self.label_6.setText(_translate("Dialog", "提示信息"))
        self.pb_exec.setText(_translate("Dialog", "执行操作"))
        self.label.setText(_translate("Dialog", "文件路径:"))


